/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SealRouteImport } from './routes/seal'
import { Route as InvokeRouteImport } from './routes/invoke'
import { Route as HoursRouteImport } from './routes/hours'
import { Route as GrimoireRouteImport } from './routes/grimoire'
import { Route as CorrespondencesRouteImport } from './routes/correspondences'
import { Route as CipherRouteImport } from './routes/cipher'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SealRoute = SealRouteImport.update({
  id: '/seal',
  path: '/seal',
  getParentRoute: () => rootRouteImport,
} as any)
const InvokeRoute = InvokeRouteImport.update({
  id: '/invoke',
  path: '/invoke',
  getParentRoute: () => rootRouteImport,
} as any)
const HoursRoute = HoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => rootRouteImport,
} as any)
const GrimoireRoute = GrimoireRouteImport.update({
  id: '/grimoire',
  path: '/grimoire',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondencesRoute = CorrespondencesRouteImport.update({
  id: '/correspondences',
  path: '/correspondences',
  getParentRoute: () => rootRouteImport,
} as any)
const CipherRoute = CipherRouteImport.update({
  id: '/cipher',
  path: '/cipher',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cipher': typeof CipherRoute
  '/correspondences': typeof CorrespondencesRoute
  '/grimoire': typeof GrimoireRoute
  '/hours': typeof HoursRoute
  '/invoke': typeof InvokeRoute
  '/seal': typeof SealRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cipher': typeof CipherRoute
  '/correspondences': typeof CorrespondencesRoute
  '/grimoire': typeof GrimoireRoute
  '/hours': typeof HoursRoute
  '/invoke': typeof InvokeRoute
  '/seal': typeof SealRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cipher': typeof CipherRoute
  '/correspondences': typeof CorrespondencesRoute
  '/grimoire': typeof GrimoireRoute
  '/hours': typeof HoursRoute
  '/invoke': typeof InvokeRoute
  '/seal': typeof SealRoute
  '/today': typeof TodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cipher'
    | '/correspondences'
    | '/grimoire'
    | '/hours'
    | '/invoke'
    | '/seal'
    | '/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cipher'
    | '/correspondences'
    | '/grimoire'
    | '/hours'
    | '/invoke'
    | '/seal'
    | '/today'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cipher'
    | '/correspondences'
    | '/grimoire'
    | '/hours'
    | '/invoke'
    | '/seal'
    | '/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CipherRoute: typeof CipherRoute
  CorrespondencesRoute: typeof CorrespondencesRoute
  GrimoireRoute: typeof GrimoireRoute
  HoursRoute: typeof HoursRoute
  InvokeRoute: typeof InvokeRoute
  SealRoute: typeof SealRoute
  TodayRoute: typeof TodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seal': {
      id: '/seal'
      path: '/seal'
      fullPath: '/seal'
      preLoaderRoute: typeof SealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoke': {
      id: '/invoke'
      path: '/invoke'
      fullPath: '/invoke'
      preLoaderRoute: typeof InvokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hours': {
      id: '/hours'
      path: '/hours'
      fullPath: '/hours'
      preLoaderRoute: typeof HoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grimoire': {
      id: '/grimoire'
      path: '/grimoire'
      fullPath: '/grimoire'
      preLoaderRoute: typeof GrimoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondences': {
      id: '/correspondences'
      path: '/correspondences'
      fullPath: '/correspondences'
      preLoaderRoute: typeof CorrespondencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cipher': {
      id: '/cipher'
      path: '/cipher'
      fullPath: '/cipher'
      preLoaderRoute: typeof CipherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CipherRoute: CipherRoute,
  CorrespondencesRoute: CorrespondencesRoute,
  GrimoireRoute: GrimoireRoute,
  HoursRoute: HoursRoute,
  InvokeRoute: InvokeRoute,
  SealRoute: SealRoute,
  TodayRoute: TodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
